image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

# Main stage
stages:
- test
- deploy

test:
  stage: test
  script:
   - npm install
   - node node_modules/istanbul/lib/cli.js cover ./tests/perform-tests.js
  coverage: '/^Statements *: (\d+\.\d+%)/'
  artifacts:
   paths:
    - coverage/
  allow_failure: false

pages:
  stage: deploy
  script:
   - mv coverage/lcov-report/ public/
  artifacts:
   paths:
    - public
   expire_in: 30 days
  only:
   - coverage_tests
