image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

# Main stages
stages:
- build
- test
- deploy

# Generate documents on every branch.
docs_gen:
  stage: build
  script:
   - npm install
   - node node_modules/.bin/esdoc
  allow_failure: false
  artifacts:
   name: plugin-documentation
   paths:
    - docs/

# Perform full tests. Executed on every other branch but the master branch.
test:
  stage: test
  script:
   - npm install
   - node ./tests/perform-tests.js
  allow_failure: false
  except:
   - development

# Perform code coverage only on the master & development branches.
cover_test:
  stage: test
  script:
   - npm install
   - node node_modules/.bin/istanbul cover ./tests/perform-tests.js coverage
  coverage: '/^Statements *: (\d+\.\d+%)/'
  artifacts:
   name: plugin-coverage
   paths:
    - coverage/
  allow_failure: false
  only:
   - master
   - development

# Upload the code coverage and documentation reports only on the master branch.
pages:
  stage: deploy
  dependencies:
   - docs_gen
   - cover_test
  script:
   - mkdir public
   - mkdir public/coverage
   - mv coverage/lcov-report/ public/coverage
   - mkdir public/docs
   - mv docs/ /public/docs
  artifacts:
   paths:
    - public
   expire_in: 30 days
  only:
   - development

