image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

# Main stage
stages:
- test
- deploy

before_script:
- npm install

Generate Coverage Report:
  stage: test
  script:
   - node node_modules/istanbul/lib/cli.js cover ./tests/perform-tests.js
  artifacts:
   paths:
    - coverage/
  allow_failure: false

Deploy Coverage Report:
  stage: deploy
  script:
   - mv coverage/ public/
  artifacts:
   paths:
    - public
   expire_in: 30 days
  only:
   - coverage_tests
